### ISSUE TITLE
Escape Quotes

### ISSUE THREAD

**Issue by lorenzleutgeb** [GitAlias/gitalias#102]
I stumbled upon multiple instances of weird unescaped double quotes. The first instance is on line 488:
https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L487-L488
Line 487 is shown for comparison. Double quotes on line 487 are correctly escaped, but those on line 488 are not.

<details>
<summary>Other instances (sometimes with context):</summary>

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L491-L492

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L497-L498

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L505-L506

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L510

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L513-L514

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L517-L518

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L524-L525

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L656-L657

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L901-L906

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L934-L939

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L967-L973

https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L1001-L1007

The line https://github.com/GitAlias/gitalias/blob/dacb817c881ebedb599a3c8662e298a32fddab7d/gitalias.txt#L1088 breaks GitHub's syntax highlighting, so I'll stop here.
</details>

How/why does this work? Would you accept a PR escaping these quotes?

**Comment by joelparkerhenderson** [comment]
Thank you! Yes you've found a bug. Yes a PR is great, thank you.
