### ISSUE TITLE
git topic-move doesn't update upstream branch name

### ISSUE THREAD

**Issue by GreenEnergyBeam** [GitAlias/gitalias#109]
I used `git topic-begin chore-cleanup` followed by `topic-move chore-dbcontext` and then `git push` I got:

```console

fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push origin HEAD:chore-cleanup

To push to the branch of the same name on the remote, use

    git push origin HEAD

To choose either option permanently, see push.default in 'git help config'.

To avoid automatically configuring an upstream branch when its name
won't match the local branch, see option 'simple' of branch.autoSetupMerge
in 'git help config'.
```

This makes me think the upstream didn't get renamed. Is it supposed to do so?

**Comment by phdru** [comment]
IMO `topic-move` should do `git push -u` at [the last line](https://github.com/GitAlias/gitalias/blob/59bea66326e7c4d8eb435862f57c09a652c196dd/gitalias.txt#L1747C5-L1747C13).

PS. And all `topic-*` aliases should join lines with `&&`, not just `;` semicolon. But that's a different story. I just looked at them for the 1st time.

**Comment by joelparkerhenderson** [comment]
Perfect, thank you so much. I just merged it.
