### ISSUE TITLE
"tags" is duplicated

### ISSUE THREAD

**Issue by Harbie34** [GitAlias/gitalias#29]
So, it does not become "tag -n1 -list".
Is this a git problem?(git 2.15.0)

**Comment by phdru** [comment]
`tags = tag` was added in 31530a3 on Aug 8, 2016. At that time alias `tags = tag -n1 --list` had already been created.

I think you simply can choose between these two, you're not obliged to copy everything to your `.gitconfig`.

**Comment by Harbie34** [comment]
I should have chosen myself what I will adopt. ;-)
Thanks!

**Comment by joelparkerhenderson** [comment]
Good catch @Harbie34, and thanks @phdru for the explanation.

I'm deleting the lesser one `tags = tag` and keeping the `--list` one, because the intent is to be able to get a list of all items, similar to the `branches` alias, suitable for iterating.
