### ISSUE TITLE
Deprecated "git stash save"

### ISSUE THREAD

**Issue by sectsect** [GitAlias/gitalias#31]
:warning: `git stash save` has been deprecated in favour of `git stash push` on git 2.16.0.

via @ https://github.com/git/git/blob/master/Documentation/RelNotes/2.16.0.txt#L34
https://git-scm.com/docs/git-stash

https://github.com/GitAlias/gitalias/blob/9803c9c597ae5e91b2680a9a93455c840e6c1ee7/gitalias.txt#L460-L479

Do you have any plans to change the above aliases?

Please consider for this change.

**Comment by joelparkerhenderson** [comment]
Good idea! Thank you for letting us know. I'll update it right now.

In general, a project goal is to keep the gitalias.txt up to date with the current release version of git, and also include in-line comments for people who may need to support older versions of git.
