### ISSUE TITLE
grep-group not in gitalias.txt file

### ISSUE THREAD

**Issue by NRKirby** [GitAlias/gitalias#33]
The readme shows the command `grep-group`

```
grep-group =  grep --break --heading --line-number
```

Since this isn't in the `gitalias.txt` file - should it be removed from the readme or added to the txt file?

(I'll happily to do a pull-request)

**Comment by phdru** [comment]
It's called [`gg`](/GitAlias/gitalias/blob/ae93d498d278dca9327a4c33ac39690f275c0596/gitalias.txt#L107). `README` should fixed because `gitalias.txt` is the reality and `README` its description. :-)

**Comment by joelparkerhenderson** [comment]
Good catch, thank you! @phdru is correct. I'll also add "grep-group" and document it.
