### ISSUE TITLE
git alias commit-to-revision

### ISSUE THREAD

**Issue by h4kuna** [GitAlias/gitalias#38]
Here is useable shortcut for commit to revision
```
[alias]
	commit-to-revision = "!f() { if [ -z \"$1\" ]; then echo 'First parameter must be hash commit id.'; return; fi; git stash && git rebase -i \"$1^\" && git stash pop && git commit --all --amend --no-edit && git rebase --continue; }; f"
```
Example:
Make change in file.
`git log`
```
95c29b4 Add topic-move
d8b21d4 Fix topic base branch
* 538094c Add topic-delete safety check
eaf8915 Fix topic-start
```
And you want commit to 538094c
```
git commit-to-revision 538094c
```
And in editor first word **pick** replace by **e**.

**Comment by phdru** [comment]
Isn't your `commit-to-revision` the same as [fixup](https://github.com/GitAlias/gitalias/blob/95c29b4f0118b2b47de20e4a86aeb09dc7f03286/gitalias.txt#L217)?

**Comment by h4kuna** [comment]
After testing it is very similar.
