### ISSUE TITLE
Add installation instructions tailored for Windows users

### ISSUE THREAD

**Issue by falktan** [GitAlias/gitalias#81]
### Suggested Change

1) In doc/install/index.md add a section with installations instructions for Windows
2) In gitalias.txt add a section with installations instructions for Windows

### Rationale

Many Windows users would not immediately know how to transfer the Linux-installation instructions to Windows.
They would usually not know what `curl`, `vi` or `~/somefile` mean

### Steps to implement

I just wanted to make sure this feature is desired. If it is I can create a PR for it.

**Comment by joelparkerhenderson** [comment]
Good idea. Yes please for a PR.

**Comment by falktan** [comment]
Here is the PR:
https://github.com/GitAlias/gitalias/pull/82

**Comment by joelparkerhenderson** [comment]
Done, thank you.
