### ISSUE TITLE
doc/install， the gitalias.txt  cannot be found

### ISSUE THREAD

**Issue by tidus5** [GitAlias/gitalias#85]
here:
https://github.com/GitAlias/gitalias/tree/main/doc/install

it says:  Download the file [gitalias.txt] but
 https://raw.githubusercontent.com/Git%20Alias/gitalias/main/gitalias.txt
shows:
404: Not Found

maybe  it should be 
 https://raw.githubusercontent.com/GitAlias/gitalias/main/gitalias.txt

**Comment by joelparkerhenderson** [comment]
You're quite right. Thank you for letting us know! I'm fixing it now.
