### ISSUE TITLE
"git chart" is not work

### ISSUE THREAD

**Issue by 868618** [GitAlias/gitalias#88]
when i run at "git chart" 

`awk: calling undefined function systime
 source line number 1`

my computer is mac m1

**Comment by phdru** [comment]
> `awk: calling undefined function systime`

It's not a bug with the GitAlias. Most probably it's a problem with your version of `awk`. Function `systime` is a GNU extension implemented in `gawk` and `mawk`; perhaps it's not available in other `awk`s.

Read `man awk` to find out if `systime` is available in your `awk`. If not — uninstall it and install `gawk` or `mawk`.

**Comment by joelparkerhenderson** [comment]
Thank you Kenny for reporting this. @phdru is correct about this being an issue with your version of `awk`.

I'm adding a new page right now for you, to help diagnose this on your system. Can you see if this page explains what you're seeing, and if you're able to follow the instructions and they fix the issue you're experiencing?

https://github.com/GitAlias/gitalias/tree/main/doc/help/awk

Thank you!

**Comment by 868618** [comment]
> Thank you Kenny for reporting this. @phdru is correct about this being an issue with your version of `awk`.
> 
> I'm adding a new page right now for you, to help diagnose the issue on your system. Can you see if this page explains what you're seeing, and if you're able to follow the instructions and they fix the issue you're experiencing?
> 
> https://github.com/GitAlias/gitalias/tree/main/doc/help/awk
> 
> Thank you!

thank u ,  With your help, the problem was solved successfully

**Comment by 868618** [comment]
> > `awk: calling undefined function systime`
> 
> It's not a bug with the GitAlias. Most probably it's a problem with your version of `awk`. Function `systime` is a GNU extension implemented in `gawk` and `mawk`; perhaps it's not available in other `awk`s.
> 
> Read `man awk` to find out if `systime` is available in your `awk`. If not — uninstall it and install `gawk` or `mawk`.

thank u， The problem has been solved
