### ISSUE TITLE
Regarding the user information displayed in commands like `git ll`

### ISSUE THREAD

**Issue by Harbie34** [GitAlias/gitalias#93]
The command `git ll` displays the committer (%cn), but wouldn't it be more standard to show the author (%an) instead? The documentation also mentions "Short/Long author field..." but it doesn't seem to match the actual behavior.

https://github.com/GitAlias/gitalias/tree/main/doc/git-ll

**Comment by joelparkerhenderson** [comment]
Yes you're correct on both counts. This is a bug. I'll fix it now.
