### ISSUE TITLE
git hew "branch name required" error

### ISSUE THREAD

**Issue by nickheniser** [GitAlias/gitalias#95]
Running on on ubuntu 22.04, installed via the personal config instructions.

```
16:35 $ git hew
f() {       hew-local-dry-run "$@" |       xargs git branch --delete ;   }; f "$@": 1: hew-local-dry-run: not found
fatal: branch name required
```

```
16:38 $ git hew master
f() {       hew-local-dry-run "$@" |       xargs git branch --delete ;   }; f "$@": 1: hew-local-dry-run: not found
fatal: branch name required
```

git hew-local-dry-run works

```
16:39 $ git hew-local-dry-run master
  fix-jaxb
  remove-spotfire
  use-java-17
```

**Comment by phdru** [comment]
It seems `f()` was moved from shell alias to git alias forgetting prepending `git` to `hew-local-dry-run` and `hew-remote-dry-run`.

A pull request would be simple.

**Comment by nickheniser** [comment]
Oof.. i should have realized that, thanks for the hint:  https://github.com/GitAlias/gitalias/pull/96
